networks:
  trans_global_network:
    driver: bridge
volumes:
  trans_database:
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - trans_global_network